console.log("Halo, dunia! // Indonesian" )
console.log("Ciao, mondo! // Italian")
console.log("Hola, mundo! // Spanish" )
console.log("Hallo, Welt! // Alemán" )
console.log("Olá mundo // Portugues" )
console.log("Привет мир // Ruso" )
console.log("Salut monde // Francés" )
console.log("Hej Verden // Danés" )
console.log("Привіт Світ // Ucraniano" )
console.log("Selam Dünya // Turco" )